# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='interface',
            field=models.CharField(default=b'eth1', max_length=500),
        ),
    ]
